/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_pencanvas_free: (a: number, b: number) => void;
export const __wbg_penstroke_free: (a: number, b: number) => void;
export const erase_hit: (a: number, b: number, c: number, d: number, e: number) => [number, number];
export const pencanvas_begin_frame: (a: number, b: number, c: number, d: number) => void;
export const pencanvas_clear_cache: (a: number) => void;
export const pencanvas_draw_keyed: (a: number, b: number, c: number) => void;
export const pencanvas_end_frame: (a: number) => void;
export const pencanvas_evict: (a: number, b: number, c: number) => void;
export const pencanvas_last_transfer: (a: number) => [number, number];
export const pencanvas_new: (a: any) => any;
export const pencanvas_new_with_fallback: (a: any, b: number) => any;
export const pencanvas_probe_mesh: (a: number, b: number, c: number) => [number, number];
export const pencanvas_resize: (a: number, b: number, c: number) => void;
export const pencanvas_retain_mesh: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => void;
export const pencanvas_stats: (a: number) => [number, number];
export const penstroke_centerline: (a: number) => [number, number];
export const penstroke_indices: (a: number) => [number, number];
export const penstroke_len: (a: number) => number;
export const penstroke_new: (a: number, b: number, c: number, d: number, e: number, f: number) => number;
export const penstroke_push: (a: number, b: number, c: number, d: number, e: number) => void;
export const penstroke_to_json: (a: number) => [number, number];
export const penstroke_vertices: (a: number) => [number, number];
export const project: (a: number, b: number, c: number, d: number, e: number) => [number, number];
export const wasm_bindgen_e91fa3817bc4b7fa___convert__closures_____invoke___js_sys_6fff18a125d5dcf7___Function_fn_wasm_bindgen_e91fa3817bc4b7fa___JsValue_____wasm_bindgen_e91fa3817bc4b7fa___sys__Undefined___js_sys_6fff18a125d5dcf7___Function_fn_wasm_bindgen_e91fa3817bc4b7fa___JsValue_____wasm_bindgen_e91fa3817bc4b7fa___sys__Undefined_______true_: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen_e91fa3817bc4b7fa___convert__closures_____invoke___wasm_bindgen_e91fa3817bc4b7fa___JsValue__core_ed718c3d60ebd546___result__Result_____wasm_bindgen_e91fa3817bc4b7fa___JsError___true_: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen_e91fa3817bc4b7fa___convert__closures_____invoke___wasm_bindgen_e91fa3817bc4b7fa___sys__JsNullable_wgpu_5036807f9837e271___backend__webgpu__webgpu_sys__gen_GpuError__GpuError___core_ed718c3d60ebd546___result__Result_____wasm_bindgen_e91fa3817bc4b7fa___JsError___true_: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen_e91fa3817bc4b7fa___convert__closures_____invoke___wasm_bindgen_e91fa3817bc4b7fa___sys__JsNullable_wgpu_5036807f9837e271___backend__webgpu__webgpu_sys__gen_GpuError__GpuError___core_ed718c3d60ebd546___result__Result_____wasm_bindgen_e91fa3817bc4b7fa___JsError___true__24: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen_e91fa3817bc4b7fa___convert__closures_____invoke___wasm_bindgen_e91fa3817bc4b7fa___sys__JsNullable_wgpu_5036807f9837e271___backend__webgpu__webgpu_sys__gen_GpuError__GpuError___core_ed718c3d60ebd546___result__Result_____wasm_bindgen_e91fa3817bc4b7fa___JsError___true__25: (a: number, b: number, c: any) => [number, number];
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
