/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_intounderlyingbytesource_free: (a: number, b: number) => void;
export const __wbg_intounderlyingsink_free: (a: number, b: number) => void;
export const __wbg_intounderlyingsource_free: (a: number, b: number) => void;
export const __wbg_sync_free: (a: number, b: number) => void;
export const intounderlyingbytesource_autoAllocateChunkSize: (a: number) => number;
export const intounderlyingbytesource_cancel: (a: number) => void;
export const intounderlyingbytesource_pull: (a: number, b: any) => any;
export const intounderlyingbytesource_start: (a: number, b: any) => void;
export const intounderlyingbytesource_type: (a: number) => number;
export const intounderlyingsink_abort: (a: number, b: any) => any;
export const intounderlyingsink_close: (a: number) => any;
export const intounderlyingsink_write: (a: number, b: any) => any;
export const intounderlyingsource_cancel: (a: number) => void;
export const intounderlyingsource_pull: (a: number, b: any) => any;
export const sync_addr: (a: number) => any;
export const sync_create: (a: number, b: number, c: any) => any;
export const sync_join: (a: number, b: number, c: number, d: number, e: number) => any;
export const sync_node_id: (a: number) => [number, number];
export const sync_peer_count: (a: number) => number;
export const sync_push: (a: number, b: number, c: number) => void;
export const sync_secret_key: (a: number) => [number, number];
export const sync_sign_presence: (a: number, b: number, c: number) => [number, number];
export const ring_core_0_17_14__bn_mul_mont: (a: number, b: number, c: number, d: number, e: number, f: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h1be5897824ed5003: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h7c8754fb4fccc717: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h137ae832b65df188: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h137ae832b65df188_22: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h137ae832b65df188_23: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h137ae832b65df188_24: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h9288e816a40a14d3: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h11cb23aadc831bd3: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h6c0bb1e4740ecbfe: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__hdd5ff820f7753c13: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
